name: Java CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        java: [ '1.8', '9.0.4', '11.0.4', '12.0.2' ]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Java ${{ matrix.java }} 
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Build with Maven
      run: mvn -V package --file pom.xml
